Repository Scar269/Ontas-bebe, pull requests merged in 2024-08, with the labels that each got.

#15 Se implementa OAuth de Google
  index.html
  index.js
  return.html
  return.js
  usuario.html
  usuario.js
Labels: enhancement

#16 Diego/Formspree
  usuario.js
Labels: enhancement, help wanted

#18 Implementación de la primera pagina de inicio
  index.css
  index.html
Labels: documentation

#20 implementación de la segunda pagina
  usuario.css
  usuario.html
Labels: documentation

#22 se crea css de tercera pagina
  return.css
  return.html
  usuario.html
Labels: enhancement

#24 responsive de pagina 3
  return.css
Labels: enhancement

#25 Implementación Geolocation
  usuario.js
Labels: enhancement

#27 Responsivo/Index
  index.css
  index.html
  return.css
  usuario.html
Labels: enhancement

#28 Diego/Página 2 responsiva
  usuario.css
Labels: enhancement

#30 Diego/responsivo
  usuario.css
Labels: enhancement
